[build]
  # バイナリ出力先を /tmp に指定
  cmd = "go build -o /tmp/todo-backend ."
  bin = "/tmp/todo-backend"
  include_ext = ["go"]
  exclude_dir = ["vendor", ".git", "frontend"]

# その他の設定（任意）
[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
